spring:
    erro:
        path: "/erro"
        whitelabel:
            enabled: true
    ldap:
        embedded:
            ldif: "classpath:test-server.ldif"
            base-dn: "dc=springframework,dc=org"
            url: "ldap://localhost:8389"
            port: 8389
            validation:
                enabled: false 
server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO