spring:

    datasource:
        url: "jdbc:oracle:thin:@10.255.1.80:1521:mapadup"
        username: "NEW_AUTENTICACAO_APL"
        password: "NEW_AUTENTICACAO_APL"
        
    erro:
        path: "/erro"
        whitelabel:
            enabled: true
            
            
# ldapsearch -x -h 192.168.2.51 -D "sis.rh" -w "m@p@2017" -b "dc=mapahomolog,dc=net" -s sub "(cn=*)" cn mail sn    
    ldap:
#         urls: "ldap://192.168.2.51"
#         port: 389
#         base: "DC=mapahomolog,DC=net"
#         username: "sis.rh"
#         password: "m@p@2017"
        embedded:
            ldif: "classpath:test-server.ldif"
            base-dn: "dc=springframework,dc=org"
            url: "ldap://localhost:8389"
            port: 8389
            validation:
                enabled: false 

server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO