server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
url: "bla"
spring:
  resource-uri: http://localhost:8090
  security:
    oauth2:
      client:
        registration:
          SEGAUT-client-oidc:
            provider: spring
            # client-id: articles-client
            client-id: SEGAUT
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
            # client-name: articles-client-oidc
            client-name: SEGAUT
          SEGAUT-client-authorization-code:
            provider: spring
            # client-id: articles-client
            client-id: SEGAUT
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized"
            scope: articles.read
            client-name: SEGAUT-client-authorization-code
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000